sitegroup: wiche_edu

deploy_tasks:
  development:
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc all
  production:
    after_deploy:
      - drush -y updb --cache-clear=0
      - drush -y cc all

shared:
  production:
    - src: files
      dst: sites/default/files
    - src: root_files
      dst: files
    - src: info
      dst: info
    - src: MentalHealth
      dst: MentalHealth
    - src: Policy
      dst: Policy
    - src: PPT
      dst: PPT
    - src: spd
      dst: spd