docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    
    - run:
        name: task0
        command: drush -y updb --cache-clear=0
        service: cli
    
    - run:
        name: task1
        command: drush -y cc all
        service: cli
    

cronjobs:
  - name: drush cron
    schedule: "*/15 * * * *"
    command: drush cron
    service: cli

environments:
  master:
    routes:
      - varnish:
        - "www.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
        - "wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
        - "wue.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
        - "wrgp.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
        - "nanslo.org":
            tls-acme: 'true'
            insecure: Redirect
        - "wiche-wue.info":
            tls-acme: 'true'
            insecure: Redirect
            - "everylearnereverywhere.org":
            tls-acme: 'true'
            insecure: Redirect
        - "www.everylearnereverywhere.org":
            tls-acme: 'true'
            insecure: Redirect
            - "everylearnereverywhere.org-0":
            tls-acme: 'true'
            insecure: Redirect
        - "www.everylearnereverywhere.org-0":
            tls-acme: 'true'
            insecure: Redirect
